version: 2

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build-test:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check Typescript Errors
          command: yarn tsc
      - run:
          name: Check Linting Errors
          command: yarn lint
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Create Code Coverage
          command: yarn test -- --coverage
  build-e2e:
    docker:
      - image: cypress/base:14.15.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run E2E Tests
          command: yarn cy:ci

workflows:
  build-test:
    jobs:
      - build-test
      - build-e2e
