version: 2.1

<<<<<<< HEAD
orbs:
  cypress: cypress-io/cypress@1

=======
>>>>>>> 18f1bb2 (write component tests (#50))
jobs:
  build-test:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: tsc
          command: npm run tsc
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: npm run test -- --coverage
<<<<<<< HEAD
  build-e2e:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: e2e
          command: npm run test:e2e:run
=======
>>>>>>> 18f1bb2 (write component tests (#50))

workflows:
  build-test:
    jobs:
      - build-test
<<<<<<< HEAD
      - build-e2e
=======
>>>>>>> 18f1bb2 (write component tests (#50))
