version: 2.1

jobs: 
  build: 
    docker:       
      - image: circleci/node:14.15.3       
    steps:       
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
  test:
    docker:       
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: npm run test -- --coverage
  deploy:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - run:
          name: deploy
          command: curl -X POST -d {} ${NETLIFY_DEPLOY_KEY}

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - test