version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build-test:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: tsc
          command: yarn tsc
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: yarn test -- --coverage
  build-e2e:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: e2e
          command: yarn cy:ci

workflows:
  build-test:
    jobs:
      - build-test
      - build-e2e
